
export const mockUsers = [
  {
    id: 1,
    fullName: "John Dube",
    email: "john.d@example.com",
    phone: "+27 73 123 4567",
    dob: "1978-01-01",
    idNumber: "7801015387082",
    nationality: "South African",
    taxNumber: "12345678901",
    taxCountry: "South Africa",
    address: "123 Main Street, Sandton",
    postalCode: "2031",
    city: "Johannesburg",
    province: "Gauteng",
    sourceOfFunds: "Employment",
    employmentStatus: "Employed",
    employer: "ABC Corporation",
    occupation: "Financial Analyst",
    riskProfile: "Moderate",
    incomeBracket: "R500,000 - R750,000",
    pep: "No",
    investmentCount: 3,
    lastLogin: "2023-04-21",
  },
  {
    id: 2,
    fullName: "Sarah Nkosi",
    email: "sarah.n@example.com",
    phone: "+27 82 987 6543",
    dob: "1985-05-15",
    idNumber: "8505155387083",
    nationality: "South African",
    taxNumber: "98765432109",
    taxCountry: "South Africa",
    address: "456 Oak Avenue, Rosebank",
    postalCode: "2196",
    city: "Johannesburg",
    province: "Gauteng",
    sourceOfFunds: "Business",
    employmentStatus: "Self-Employed",
    employer: "",
    occupation: "Business Owner",
    riskProfile: "Aggressive",
    incomeBracket: "R750,000 - R1,000,000",
    pep: "No",
    investmentCount: 2,
    lastLogin: "2023-04-18",
  },
];

export const mockBeneficiaries = [
  {
    id: 1,
    userId: 1,
    beneficiaryName: "Sarah Dlamini",
    relationship: "Spouse",
    phone: "073 123 4567",
    email: "sarah.d@example.com",
    type: "Primary",
    percentage: 60
  },
  {
    id: 2,
    userId: 1,
    beneficiaryName: "Thabo Dlamini",
    relationship: "Son",
    phone: "082 987 6543",
    email: "thabo.d@example.com",
    type: "Secondary",
    percentage: 40
  }
];
