// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tryalfcdjznmtqaxungq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeWFsZmNkanpubXRxYXh1bmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTI4MTQsImV4cCI6MjA2MDk4ODgxNH0._XYmGytljn08MWctZ18fj0TLnMZ08awj46G5BXHiAI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);